# Bridging the Generation Gap

The older generation feels there is a generation gap between the younger generation. This is apparently a simple way of communication, dressing, digital skills and Curriculum of education. Even the older generation taught harshly to give an information to the learners, on the other hand of younger generation feels so advance in education and information through the internet.
In the field of education, the existence gap in generation are continuing to grow up unless the changes of generation are adopted. The dominance of digital technology has spread that generation gap becoming wider, as young people become conversant with mobile digital devices, games and social media that didn’t exist when their teachers were growing up.

## Generation 

the average span of time between the birth of parents
and that of their offspring

**Four Generation**

- BABY Boomers – Bloom in the mid-century.
- GEN X – Born early-to-mid 1960’s – early 1980’s
- GEN Y – Born after 1981
- GEN Z (ALPHA) – Birth between 1995 and 2019

**Gap** - a space between two things

**Generation Gap** - Wide differences in cultural norms between the younger generation and the elder

**Older Generation**
- Often feels that there is a generation gap between them and the younger generation.
- The gap is apparent in simple things like **manner of dressing, way of socializing, entertainment, intimate relationships,** etc.

##Mode of Learning

In the field of education, a huge generation gap also exists and it will continue to widen unless some changes are adopted at the proper time.

**For Example:**

- The educational curriculum is low compared to the other countries
- In peasant third world countries where schools don’t have technology facilities, it is understandable, that the transition to digital education may take time. But given the rapid
emergence of digital technology, at times referred to as information and communication technology (ICT), there is the need to prepare for bridging the digital gap in the society.

**Information and Communication Technology**

- The use of hardware and software for efficient management of
information.
- Refers to the forms of technology that are used to transmit,
store, create, share or exchange particular task.

**Understanding Potential of ICT**

- The new network of instantaneous communication is global,
overcoming, borders between countries and continents.
- Much of what elders believe may not applicable anymore to the
new generation, especially along matters of traditional value.