# Understanding Technology Learners

Our Teachers today generally use the traditional education program applicable to
Learners of the past, acquainted with linear, textual and sequential learning. They fail to
realize that the new generation 21st millennium is the kind of learners that they were,
but are information technology or digital learners. The 21st century education is going to
be empowered by digital learners pretty soon as the is beginning is coming.

- 53% of students use a smart phone and are concerned and prefer the internet.
- 78% of the students believe and prefer learning through technology.

Even in classes, their concentration is questionable as they are uneasy to simply sit
and listen. They become alive again through video presentations, group activities and
computer classes. Information technology learners (Digital Learners) - A video
presentation is discussing the characteristics of a digital learner

## Learner

**Traditional Learner** – basically, a leaner who makes use of traditional ways of learning;
one who studies from books and other second sources of information.

**Technology Learner**- Anyone who makes use of man-made inventions such as books
in learning. However, in the context of Educational Technology, we are referring
to Technology learner’s as Digital Learner’s, a learner who learns with the use of
technology, anything that is digital.

## 21st Century Learning

**Collaboration**

learning how to work with others to achieved a common purpose. Students bring gadgets with them as well as presenting the knowledge the knowledge
and abilities they have to come up with a product solution.

**Communication**

Students use mobile
devices to discuss content they are learning
with others, set goals for themselves, and
share new concepts. The Lines of
communication now become multi- directional
and extend beyond the classroom.

**Critical Thinking**

helps to construct a
firm foundation for personalized learning in
many classrooms, teachers don't provide the
time necessary for critical thinking in order to
develop original solutions to problems, many
of the problems that are provided to students
also have only one possible right or wrong
answer don't encourage true critical thinking.

**Creativity**

Students make use of their
imagination as well as technologies to create
new things to think beyond things.

## Today's Learner

Today’s learners appear smarter, yet they can’t read as their parents do and they are
addicted to the internet.

- Even in classes, their concentration is questionable as they are uneasy to simply sit and listen. They become alive again through video presentations, group activities and computer classes.
- It is to be admitted that our teachers today generally use the traditional education program applicable to learners of the past, acquainted with linear,
textual, and sequential learning.
- They fail to realize that the new generation of the 21st millennium is not the kind of learner that they were, but are information technology or digital learners.
- The new learners spend much time talking with friends on their cell phones,
sending text messages, interacting through Internet media like Facebook, playing video games and surfing the World Wide Web.

## Generalization

In general Understanding technology learner’s Learners these days are more store of visual presentation made or displayed by their educators more than simply unadulterated tuning in. They are likewise not intrigued much in the discourse if there's nothing to pull in them. Some way or another, having this new innovation made the method for showing too hard in light of the fact that the instructor MUST have or get something quite recently to draw in their understudies dissimilar to before everything was so basic. In any case, then, we must adapt up to what our surroundings are currently into, and that is fundamentally Innovation. It is on us on how we keep it adjust without going up against its harsh path for both educator and learners. How about we make utilization of it on a way it could help and we can learn. Not to damage by any stretch of the imagination. The new generation of the 21st millennium is not the kind of learner that they were, but are information technology or digital learners.