# Preferences of Technology Generation

What the old generation likes may not be the same as what the new generation
prefers in their life, work and leisure. Sad to say, much of the good things enjoyed by
elders when they were students are no longer available to the new generation. Post-war
II gardening classes in which students engaged in seedbed preparation, planting and
nurturing of vegetables plants in wide school grounds are no longer part of the school
program. Vocational, cultural and values classes have also been minimized due to
emphasis on the basics of English, Mathematics and Science.

The state dictates educational priorities based on perceptions on the country’s
nee to strengthen its agricultural, business or industrial economy. As technology stages
a change along a global dimension, lawmakers are challenged to adopt wisdom in
calibrating the genuine needs of development and not be copycats of other nations,
forgetting indigenous potentials in people, land, mineral resources, forestry, and sea
space which make the country rich for long term

## Difference between Old and Young Generation

**Text versus Visuals**

Our parents read book texts, enriched by illustrations and photos. In order to
research, they go to the school library, use the card catalogue of needed books, and
sign up to borrow books for home reading. The technology or digital generation has
greater affinity to visuals (photos and video) compared with texts. In fact, they have
been exposed since childhood to cable television and video images especially cartoon
characters, and then to computer images, in such a manner that their visual fluency. Or
abilities have been sharpened and enhanced.

**Linear versus Hypermedia**

The past-30-year-old generation has obtained information in a linear, logical and
sequential manner. On the positive side, this has made them more logical, focused, and
reflective thinkers. The new generation, however, follow a personal random access to
hyperlinked digital information, less superior to elders in focus and reflection. Thus, they
appear to be more easily bored and distracted during class lectures.

**Independent vs Social Learners**

The traditional education system gives priority to independent learning, prior to
participative work. New learners, however, are already acquainted with digital tools that
adopt to both personal and participative work. They take opportunity for dozens of
instantaneous ways to communicate with other-mobile calls and texts, emails,
Facebook, Youtube, MySapce, Twitter wikis, etc. Experts describe this mode of digital
learning as one that is based on experimentation, discovery and intuition.

**Learning to do vs Learning to pass the test**

Old teachers teach students in order to help them to pass the test and complete
the course requirement. On the other hand, new digital learners simply wish to acquire
skills, knowledge and habits as windows of opportunity afford them to learn. ur parents
have complete course and have engaged in a permanent job for most of their lives. A
different work situation awaits the digital generation with the contractual, multitasked,
and multi-career opportunities in a general world ahead of them

**Delayed rewards and instant gratification**

The traditional reward system in education consist in the grades, honor
certificates/medals, and diplomas. Including future jobs, the traditional school’s reward
system consist of unclear rewards for performance.
On the other hand digital learners on their own experience more immediate
gratification through immediate scores from games, enjoyable conversation from web
cam calls, excitement from email chats, and inviting comments from their Facebook
account.

**Rote memory vs Fun Learning**

Teacher feel obliged to delivering content-based courses, the learning of which is
measurable by standard test. Digital learners prefer fun learning which relevant and
instantaneously useful to them.

Learning is play to a new learner and not surprisingly there is much fun in the
digital world outside the school.

Teacher need connect with digital learners, and not think of them as entering their past-
30 years old traditional world. While there are apparent set back limitation to digital
learning, there are opportunities to tap through:

- The new learners digital fluency with visual learning with the use of audio visuals,
media and multimedia
- Using hyperlinked multimedia for projects that enhance work focus and reflection;

- Problem solving Activities to suit the new generation’s style and preference for
fun and relevant learning.

## Generalization

To put it all together, even though the older generation may have a big gap to the
younger generation, older generation is also trying to adapt on technology. And they
may not be as good compared to us when it comes to the trend now days; they also
have great experience on their own that the today’s generation is not able to
experience. We all know that technology is the way of everyone to everything now days.
And that one of the reason that we should share our knowledge in technology to much
older people than us for them also to experience the new normal of our generation
whether they will agree or not. It’s also our ways for them to understand and us also to
understand the gap our generation. We may have different perceptions on things but we
have similar goals and we just express or apply them differently.